export default {
  // State
  COMMENT_DATA_SUBMITTING: 'COMMENT_DATA_SUBMITTING',
  COMMENT_DATA_UPDATED: 'COMMENT_DATA_UPDATED',
  DELETE_COMMENT: 'DELETE_COMMENT',
  COMMENT_DELETED: 'COMMENT_DELETED',
  // Status
  COMMENT_RESPONSE_FAILURE: '@@/comment:CODE2XX',
  COMMENT_DELETE_FAILURE: '@@/comment:CODE2xx'
};
