export default {
  // Actions
  QUESTION_DETAIL_GET: 'GET@@/question/detail',
  // State
  QUESTION_DATA_SUBMITTING: 'QUESTION_DATA_SUBMITTING',
  QUESTION_DATA_UPDATED: 'QUESTION_DATA_UPDATED',
  // Status
  QUESTION_RESPONSE_FAILURE: '@@/question:CODE2XX',
};
