export default {
  // Actions
  QUESTION_DETAIL_GET: 'GET@@/question/detail',
  // State
  QUESTION_DATA_SUBMITTING: 'QUESTION_DATA_SUBMITTING',
  QUESTION_DATA_UPDATED: 'QUESTION_DATA_UPDATED',
  DELETE_QUESTION: 'DELETE_QUESTION',
  QUESTION_DELETED: 'COMMENT_DELETED',
  // Status
  QUESTION_RESPONSE_FAILURE: '@@/question:CODE2XX',
  QUESTION_DELETE_FAILURE: '@@/comment:CODE2xx'
};
