export default {
  // Action
  // State
  QUESTION_VOTE_UP_SUBMITTING: 'QUESTION_VOTE_UP_SUBMITTING',
  QUESTION_VOTE_DOWN_SUBMITTING: 'QUESTION_VOTE_DOWN_SUBMITTING',
  QUESTION_VOTE_UP_SUBMITED: 'QUESTION_VOTE_UP_SUBMITED',
  QUESTION_VOTE_DOWN_SUBMITED: 'QUESTION_VOTE_DOWN_SUBMITED',
  // Status
  QUESTION_VOTE_FAILURE: '@@/profile:CODE4xx',
};
